### ISSUE TITLE
Pyno requires pyglet 1.5.27 and a patch on Python 3.11

### ISSUE THREAD

**Issue by ClaudioGi** [honix/Pyno#47]
See below how to make it run on Python 3.11 and why it fails with pyglet version 2.0.7: 

```
import pyglet #o#0#o# requires pyglet version 1.5.27
# With pyglet 2.0.7 there is an error:
#   File "~/.local/lib/python3.11/site-packages/pyno/draw.py", line 7, in <module>
#     class UIGroup(pyglet.graphics.OrderedGroup):
#                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# AttributeError: module 'pyglet.graphics' has no attribute 'OrderedGroup'
# Because: 
# pyglet-2.0.7/doc/programming_guide/migration.rst:50:`OrderedGroup` has been removed. Instead, all Groups now have an `order`

from inspect import getfullargspec as getargspec  #o#0#o# OK on Python 3.11
# from inspect import getargspec # fails on Python 3.11 with:
#     from inspect import getargspec  
#     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# ImportError: cannot import name 'getargspec' from 'inspect' (/usr/local/lib/python3.11/inspect.py)
```

**Comment by GurePortela** [comment]
Oi não consigo rodar o aplicativo no windows 10 mesmo instalando a versão
pyglet 1.5.2,depois de muitas tentativas importando:
Для


Привет, я не могу запустить приложение в Windows 10, даже установив версию
pyglet 1.5.2 после многих попыток импорта:

import pyno
pyno.app_run()

 dava erro tipo :выдало ошибку вроде

'Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    pyno.app_run()
AttributeError: module 'pyno' has no attribute 'app_run'

Só rodou quando fiz: Он работал только тогда, когда я делал:
>>> import pyglet
>>> import window
>>> import profile
>>> import pyno
>>> pyno.run()
Loading...
Can't load file: [Errno 2] No such file or directory: '.auto-saved.pn'
File C:\Python39\lib\site-packages\pyno\examples\welcome.pn loaded!
New pyno!
New window!
Connection is broken:
File .auto-saved.pn saved!
File .auto-saved.pn saved!
File .auto-saved.pn saved!
File .auto-saved.pn saved!
File .auto-saved.pn saved!
File .auto-saved.pn saved!




Em qui., 11 de mai. de 2023 às 18:08, ClaudioGi ***@***.***>
escreveu:

**Comment by GurePortela** [comment]
oi
no windows 10 o texto dos nós esta sumindo quando vc desloca o no pela tela

В Windows 10 текст узлов исчезает, когда вы перемещаете узел по экрану

Em ter., 25 de jul. de 2023 às 12:34, GurePortela ***@***.***>
escreveu:
